/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.5/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application.
    application
    id("org.openjfx.javafxplugin") version "0.0.9"

}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    flatDir {
        dirs("lib")
    }
    jcenter()
}


java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

javafx {
    version = "17.0.1"
    modules = listOf("javafx.controls", "javafx.fxml", "javafx.web", "javafx.swing")
}


tasks.compileJava {
    options.encoding = "UTF-8"
}

sourceSets {
    main {
        resources {
            srcDir("src/main/java")
            includes.add("**/*.*")
        }
    }
}



dependencies {
    implementation(files("./lib/apktool_2.4.0.jar"))
    implementation("com.google.guava:guava:29.0-jre")
    implementation("com.google.protobuf:protobuf-java:3.7.0")
    implementation("com.mortennobel:java-image-scaling:0.8.6")
    implementation("commons-codec:commons-codec:1.11")
    implementation("commons-io:commons-io:2.6")
    implementation("commons-logging:commons-logging:1.2")
    implementation("org.apache.commons:commons-compress:1.17")
    implementation("org.apache.commons:commons-lang3:3.7")
    implementation("org.apache.httpcomponents:httpclient:4.5.5")
    implementation("org.json:json:20180130")

    testImplementation("junit:junit:4.13")
}

application {
    // Define the main class for the application.
    mainClassName = "com.xiaomitool.v2.gui.MainWindow"
}
